### ISSUE TITLE
Sass support not working

### ISSUE THREAD

**Issue by RubberDuckShobe** [gushogg-blake/svelte-view-engine#1]
Hello, I'm trying to use this together with Sass and Bulma, however it seems that processing Sass files doesn't work correctly.

This is my scss file, importing Bulma's files from node_modules
```scss
@import "https://use.fontawesome.com/releases/v5.3.1/css/all.css";

:root {
    padding: 2em;
}

$primary: #2196f3;
$link: #2196f3;

@import "bulma/sass/utilities/_all.sass";
@import "bulma/sass/base/_all.sass";
@import "bulma/sass/helpers/_all.sass";
@import "bulma/sass/elements/button.sass";
@import "bulma/sass/elements/container.sass";
@import "bulma/sass/elements/title.sass";
@import "bulma/sass/elements/image.sass";
@import "bulma/sass/components/navbar.sass";
@import "bulma/sass/layout/section.sass";
```

This is the only stylesheet file that gets served to the browser:
```scss

			@import "https://use.fontawesome.com/releases/v5.3.1/css/all.css";

:root {
    padding: 2em;
}

$primary: #2196f3;
$link: #2196f3;

@import "bulma/sass/utilities/_all.sass";
@import "bulma/sass/base/_all.sass";
@import "bulma/sass/helpers/_all.sass";
@import "bulma/sass/elements/button.sass";
@import "bulma/sass/elements/container.sass";
@import "bulma/sass/elements/title.sass";
@import "bulma/sass/elements/image.sass";
@import "bulma/sass/components/navbar.sass";
@import "bulma/sass/layout/section.sass";
			undefined
		
```

However, I have noticed that you are using the deprecated ``node-sass`` instead of the new ``sass`` package, but I don't know if that has anything to do with the issue.

Any help would be appreciated.
